import Head from 'next/head';
import Layout from '@/layout/Layout';
import { trpc } from '../utils/trpc';
import Link from 'next/link';




export default function Home() {
  const {data, isLoading, isError} = trpc.bookQuerys.get.useQuery();
 


  if (isLoading) 
  if (isError)return <div>error</div>
  if (!data) return <div>No data found</div>;


  return (
    <>
      <Head>
        <title>eBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>


      </Layout>

     

    </>
  )
}
