import Head from "next/head";
import Layout from "@/layout/Layout";
import { trpc } from "../utils/trpc";
import Link from "next/link";

import Catacpol from "@/components/ux/Catacpol";
import Welcome from "@/components/sections/Welcome";
import Contact from "@/components/sections/Contact";
import About from "@/components/sections/About";
import War from "@/components/ux/War";

export default function Home() {
  return (
    <>
      <Head>
        <title>C.A.Tac.Pol.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main >


          <div className="flex  z-50">
              <div className=" w-screen z-30">

              <Catacpol />
              </div>

         
          </div>

    

          <div className="section z-30 justify-center  flex gap-6 w-full ">
            <div className="max-w-[800px] z-30 flex flex-col  gap-6">
              <Welcome />
              <About />

       
  
            </div>

          </div>
          
              <Contact />


          <War />
        </main>
      </Layout>
    </>
  );
}
